/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/admin-login`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/photo-capture`; params?: Router.UnknownInputParams; } | { pathname: `/review-submit`; params?: Router.UnknownInputParams; } | { pathname: `/visitor-entry`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/admin-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/admin-login`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/photo-capture`; params?: Router.UnknownOutputParams; } | { pathname: `/review-submit`; params?: Router.UnknownOutputParams; } | { pathname: `/visitor-entry`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/admin-dashboard${`?${string}` | `#${string}` | ''}` | `/admin-login${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/photo-capture${`?${string}` | `#${string}` | ''}` | `/review-submit${`?${string}` | `#${string}` | ''}` | `/visitor-entry${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/admin-login`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/photo-capture`; params?: Router.UnknownInputParams; } | { pathname: `/review-submit`; params?: Router.UnknownInputParams; } | { pathname: `/visitor-entry`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
